apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: jaeger-gtw
  namespace: default
spec:
  gatewayClassName: eg
  listeners:
    - name: query
      protocol: HTTP
      port: 16686
    - name: collector
      protocol: HTTP
      port: 14268