apiVersion: tracing.orange.io/v1alpha1
kind: Jaeger
metadata:
  name: all-in-one-with-route
  namespace: default
spec:
  type: allInOne
  extensions:
    httpRoutes:
      - target: query
        targetPort: 16686
        parentRef:
          name: jaeger-gtw
          sectionName: query
          port: 16686
      - target: collector
        targetPort: 14268
        parentRef:
          name: jaeger-gtw
          sectionName: collector
          port: 14268
  components:
    allInOne:
      setting:
        args:
          - "--memory.max-traces=100"
        envs:
          - name: JAEGER_DISABLED
            value: "true"
  commonSpec:
    metadata:
      annotations:
        env: dev-env
    service:
      type: ClusterIP