apiVersion: tracing.orange.io/v1alpha1
kind: Jaeger
metadata:
  name: distribute-es
  namespace: default
spec:
  type: distribute
  components:
    storage:
      type: elasticsearch
  commonSpec:
    httpRoutes:
      - target: query
        targetPort: 16686
        parentRef:
          name: eg
          port: 16686
      - target: collector
        targetPort: 14268
        parentRef:
          name: eg
          port: 14268